name: learn_github_actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
#on:
#  release:
#    types: [published]
jobs:
  Update_version_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - run: ls -l
